name: Build / Release

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build-release:
    name: ${{ matrix.targets.alias }}
    runs-on: ${{ matrix.targets.os }}

    strategy:
      fail-fast: false
      matrix:
        targets:
          # mac
          - { os: macos       , target: aarch64-apple-darwin     , alias: aarch64-apple-darwin       }
          - { os: macos       , target: x86_64-apple-darwin      , alias: x86_64-apple-darwin        }
          # linux
          - { os: linux       , target: x86_64-unknown-linux-gnu , alias: x86_64-unknown-linux-gnu   }
          - { os: linux       , target: x86_64-unknown-linux-musl, alias: x86_64-unknown-linux-musl  }
          # freebsd
          - { os: freebsd     , target: x86_64-unknown-freebsd   , alias: x86_64-unknown-freebsd     }
          # windows
          - { os: windows     , target: x86_64-pc-windows-msvc   , alias: x86_64-pc-windows-msvc     }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # github.ref 变量将自动填充为触发事件的分支或标签名
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Setup musl-tools
        if: matrix.targets.target == 'x86_64-unknown-linux-musl'
        shell: bash
        run: sudo apt -y install musl-tools

      - name: Add target
        uses: ./.github/actions/add-target
        with:
          target: ${{ matrix.targets.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.targets.alias }}

      - name: Generate version
        id: gen-version
        shell: bash
        run: echo 'VERSION=${{ github.ref_name }}' | sed 's/v//' >> $GITHUB_OUTPUT

      - name: Replace version
        uses: ./.github/actions/replace-version
        with:
          version: ${{ steps.gen-version.outputs.VERSION }}

      - name: Run build
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.targets.target }}
          release: true

      - name: Generate artifacts name
        id: gen-name
        shell: bash
        run: echo 'NAME=cnb-${{ steps.gen-version.outputs.VERSION }}-${{ matrix.targets.alias }}' >> $GITHUB_OUTPUT

      - name: Generate binary extension
        id: gen-ext
        if: runner.os == 'Windows'
        shell: bash
        run: echo 'EXT=.exe' >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.gen-name.outputs.NAME }}
          path: ./target/${{ matrix.targets.target }}/release/cnb${{ steps.gen-ext.outputs.EXT }}
          if-no-files-found: error

      - name: Archive binary
        uses: ./.github/actions/make-archive
        with:
          files: ./target/${{ matrix.targets.target }}/release/cnb${{ steps.gen-ext.outputs.EXT }}
          out: ${{ steps.gen-name.outputs.NAME }}.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.gen-name.outputs.NAME }}.zip
